### ISSUE TITLE
/posts/22-12-02/

### ISSUE THREAD

**Issue by ryan4yin** [chengleqi/chengleqi.github.io#1]
<https://chengleqi.com/posts/22-12-02/>

读文章意外发现，文末的容器网络图似曾相识，貌似是我画的哈哈～

**Comment by chengleqi** [comment]
我也曾看过你的博客，获益匪浅，这个容器网络图确实是复制的，需要的话俺可以删掉，或者我注明您的博客地址？

**Comment by ryan4yin** [comment]
@chengleqi 嗯帮到了别人就是我分享这些笔记的初衷，不过你把参考过的资料列一下就更好了。
顺便你做了好多项目，有机会可以交流交流 🤣，我在 0xffff 社区比较活跃，欢迎来社区分享学习 xv6 或者搞其他云原生项目之类的，有意思的技术内容：

<https://0xffff.one/>

**Comment by chengleqi** [comment]
> @chengleqi 嗯帮到了别人就是我分享这些笔记的初衷，不过你把参考过的资料列一下就更好了。 顺便你做了好多项目，有机会可以交流交流 🤣，我在 0xffff 社区比较活跃，欢迎来社区分享学习 xv6 或者搞其他云原生项目之类的，有意思的技术内容：
> 
> https://0xffff.one/

多谢 我会注意的～
